"""Label-printing pages: pick a kind/template/record, preview, download the
print-ready PDF.

A separate router from ``cuore.web.routes`` and ``cuore.web.service_routes``
(both were being edited/created concurrently by other agents while this was
built) but the same posture: the page and the JSON endpoint below call the
same :mod:`cuore.services.labels_bridge` functions, so they cannot disagree.

Page set:

===========================  ==================================================
``/v/{vin}/labels``          pick kind/template/record, preview, download link
``/v/{vin}/labels.pdf``      the print-ready PDF (or the test grid)
===========================  ==================================================

Not registered on the app here -- ``app.py`` is owned by another agent while
this was built. The two lines needed there (next to the other web-route
imports, as ``from .web import labels_routes``):

    ``app.include_router(labels_routes.router)``
    ``app.include_router(labels_routes.api_router, prefix="/api")``

No JavaScript: every control that changes what the page needs to show
(kind, template, record) is a plain form field that auto-submits via a
non-JS-required ``<select onchange="this.form.submit()">`` -- the same
progressive-enhancement pattern ``service_routes.py`` uses for its category
selector. The "preview" is the actual PDF for one copy, embedded with
``<embed>``, generated by the exact same code path as the download -- there
is no separate preview renderer to drift out of sync.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Optional

from fastapi import APIRouter, Depends, Request
from fastapi.responses import HTMLResponse, Response
from fastapi.templating import Jinja2Templates

from .. import __version__
from ..services import cache, labels_bridge, mes_bridge
from ..services.errors import BridgeError
from ..api.deps import require_token, settings_of

HERE = Path(__file__).resolve().parent
TEMPLATE_DIR = HERE / "templates"

templates = Jinja2Templates(directory=str(TEMPLATE_DIR))

router = APIRouter(include_in_schema=False,
                   dependencies=[Depends(require_token)])

api_router = APIRouter(tags=["labels"], dependencies=[Depends(require_token)])

_VIN_COOKIE = "cuore_vin"

_OVERRIDE_FIELDS = (
    "shop_name", "date", "odometer_km", "oil_viscosity", "oil_spec",
    "quantity_l", "filter_part_no", "technician", "next_due_km",
    "next_due_mi", "next_due_date", "section", "work_done", "next_due",
    "key_spec", "key_torque", "component", "torque_key", "torque_nm",
    "torque_lbft", "angle", "vehicle", "job",
)


# --- helpers (small, deliberate duplicates of cuore.web.routes's private
#     helpers -- see service_routes.py for the same rationale) --------------


def _dossier(vin: str) -> dict[str, Any]:
    try:
        return cache.get_or_build(
            ("workup", vin, mes_bridge.newest_mtime(vin)),
            lambda: mes_bridge.workup(vin=vin),
        )
    except BridgeError:
        return {"identity": {}}


def _vehicle_bar(vin: str, dossier: dict[str, Any]) -> dict[str, Any]:
    ident = dossier.get("identity", {})
    first, last = ident.get("odometer_first_km"), ident.get("odometer_last_km")
    span = None
    if isinstance(first, (int, float)) and isinstance(last, (int, float)):
        span = int(last) - int(first)
    return {
        "vin": vin,
        "name": ident.get("vehicle") or "(unnamed vehicle)",
        "logs": ident.get("log_count"),
        "first_log": ident.get("first_log"),
        "last_log": ident.get("last_log"),
        "odo_first": first,
        "odo_last": last,
        "odo_span": span,
        "ecus": ident.get("ecu_seen") or [],
    }


def _page(request: Request, name: str, **ctx: Any) -> HTMLResponse:
    settings = settings_of(request)
    ctx.setdefault("version", __version__)
    ctx.setdefault("profile", settings.profile.value)
    ctx.setdefault("live_strip", None)
    return templates.TemplateResponse(request, name, ctx)


def _bool_q(v: Optional[str]) -> bool:
    return str(v or "").strip().lower() in ("1", "true", "on", "yes")


def _int_q(v: Optional[str], default: int) -> int:
    try:
        return int(str(v).strip())
    except (TypeError, ValueError):
        return default


def _float_q(v: Optional[str], default: float = 0.0) -> float:
    try:
        return float(str(v).strip())
    except (TypeError, ValueError):
        return default


def _overrides_from(q: dict[str, Any]) -> dict[str, Any]:
    out = {}
    for f in _OVERRIDE_FIELDS:
        v = q.get(f)
        if v not in (None, ""):
            out[f] = v
    if _bool_q(q.get("single_use")):
        out["single_use"] = True
    elif "single_use" in q:
        out["single_use"] = False
    return out


def _custom_from(q: dict[str, Any]) -> Optional[dict[str, Any]]:
    if q.get("template_id") != "custom":
        return None
    try:
        return {
            "page_w_mm": float(q.get("c_page_w_mm") or 215.9),
            "page_h_mm": float(q.get("c_page_h_mm") or 279.4),
            "label_w_mm": float(q.get("c_label_w_mm") or 50),
            "label_h_mm": float(q.get("c_label_h_mm") or 25),
            "cols": int(q.get("c_cols") or 4),
            "rows": int(q.get("c_rows") or 10),
            "margin_top_mm": float(q.get("c_margin_top_mm") or 10),
            "margin_left_mm": float(q.get("c_margin_left_mm") or 10),
            "pitch_x_mm": float(q["c_pitch_x_mm"]) if q.get("c_pitch_x_mm") else None,
            "pitch_y_mm": float(q["c_pitch_y_mm"]) if q.get("c_pitch_y_mm") else None,
            "name": q.get("c_name") or "Custom",
        }
    except (TypeError, ValueError):
        return None


def _start_index(q: dict[str, Any], cols: int) -> int:
    if q.get("start_row") or q.get("start_col"):
        row = _int_q(q.get("start_row"), 1) - 1
        col = _int_q(q.get("start_col"), 1) - 1
        return max(0, row) * cols + max(0, col)
    return _int_q(q.get("start_index"), 0)


# --- labels page -------------------------------------------------------------


@router.get("/v/{vin}/labels", response_class=HTMLResponse)
def labels_page(request: Request, vin: str) -> HTMLResponse:
    q = dict(request.query_params)
    dossier = _dossier(vin)
    kind = q.get("kind") or "oil_change"
    template_id = q.get("template_id") or "avery_5520"

    tmpl_info = labels_bridge.list_templates()
    records = []
    try:
        records = labels_bridge.list_records(vin, kind) if kind in (
            "oil_change", "service", "brakes_wheels_tires", "drivetrain") else []
    except BridgeError:
        records = []
    records = list(reversed(records))  # newest first for the picker

    error = None
    preview_url = None
    try:
        custom = _custom_from(q)
        template = labels_bridge.get_template(template_id, custom)
        cols = template.cols
        start_index = _start_index(q, cols)
        if 0 <= start_index < template.count:
            params = dict(q)
            params.update({"kind": kind, "template_id": template_id,
                          "copies": "1", "start_index": str(start_index)})
            from urllib.parse import urlencode
            preview_url = f"/v/{vin}/labels.pdf?{urlencode(params)}"
    except BridgeError as exc:
        error = str(exc)
        template = None

    response = _page(request, "labels.html", vin=vin, bar=_vehicle_bar(vin, dossier),
                     tab="labels", templates_list=tmpl_info["templates"],
                     kinds=tmpl_info["kinds"], records=records, q=q,
                     kind=kind, template_id=template_id, error=error,
                     preview_url=preview_url,
                     current_odometer=(dossier.get("identity") or {}).get("odometer_last_km"))
    response.set_cookie(_VIN_COOKIE, vin, max_age=60 * 60 * 24 * 30, samesite="lax")
    return response


@router.get("/v/{vin}/labels.pdf")
def labels_pdf(request: Request, vin: str) -> Response:
    q = dict(request.query_params)
    kind = q.get("kind") or "oil_change"
    template_id = q.get("template_id") or "avery_5520"
    custom = _custom_from(q)
    overrides = _overrides_from(q)
    record_id = q.get("record_id") or ""
    copies = max(1, _int_q(q.get("copies"), 1))
    offset_x_mm = _float_q(q.get("offset_x_mm"), 0.0)
    offset_y_mm = _float_q(q.get("offset_y_mm"), 0.0)
    qr_url = q.get("qr_url") if _bool_q(q.get("qr")) else None

    template = labels_bridge.get_template(template_id, custom)

    if _bool_q(q.get("grid")):
        pdf = labels_bridge.render_test_grid(template_id, custom,
                                             offset_x_mm=offset_x_mm,
                                             offset_y_mm=offset_y_mm)
        fname = f"label-test-grid-{template_id}.pdf"
    else:
        start_index = _start_index(q, template.cols)
        pdf = labels_bridge.render_pdf(
            vin=vin, kind=kind, template_id=template_id, record_id=record_id,
            overrides=overrides, custom=custom, copies=copies,
            start_index=start_index, offset_x_mm=offset_x_mm,
            offset_y_mm=offset_y_mm, qr_url=qr_url)
        fname = f"label-{kind}-{vin}.pdf"

    return Response(content=pdf, media_type="application/pdf",
                    headers={"Content-Disposition": f'inline; filename="{fname}"'})


# --- JSON API ----------------------------------------------------------------


@api_router.get("/vehicles/{vin}/labels/templates")
def api_label_templates(vin: str) -> dict[str, Any]:
    # vin accepted for a consistent per-vehicle URL shape (matching every
    # other /api/vehicles/{vin}/* route) -- the template catalogue itself is
    # not vehicle-specific.
    return labels_bridge.list_templates()


__all__ = ["router", "api_router", "templates", "TEMPLATE_DIR"]
